# Menghitung Jarak (Tugas 1)

Link colab tugas 1 : 

https://colab.research.google.com/drive/13gjMPa9mg_IbUASNaeKPdYxCr_nFhSQ1#scrollTo=LDSPTqfuMUfM

In [ ]:
# import library
import numpy as np
import pandas as pd
import seaborn as sb
%matplotlib inline
import matplotlib.pyplot as plt
import math

In [ ]:
#menampilkan data
data = pd.read_csv("https://raw.githubusercontent.com/rifqi-522/datamining/main/car_price_prediction.csv")
print(data)

             ID  Price  Levy   Manufacturer    Model  Prod. year   Category  \
0      45654403  13328  1399          LEXUS   RX 450        2010       Jeep
1      44731507  16621  1018      CHEVROLET  Equinox        2011       Jeep
2      45774419   8467     -          HONDA      FIT        2006  Hatchback
3      45769185   3607   862           FORD   Escape        2011       Jeep
4      45809263  11726   446          HONDA      FIT        2014  Hatchback
...         ...    ...   ...            ...      ...         ...        ...
19232  45798355   8467     -  MERCEDES-BENZ  CLK 200        1999      Coupe
19233  45778856  15681   831        HYUNDAI   Sonata        2011      Sedan
19234  45804997  26108   836        HYUNDAI   Tucson        2010       Jeep
19235  45793526   5331  1288      CHEVROLET  Captiva        2007       Jeep
19236  45813273    470   753        HYUNDAI   Sonata        2012      Sedan

      Leather interior Fuel type Engine volume    Mileage  Cylinders  \
0                  Yes    Hybrid           3.5  186005 km        6.0
1                   No    Petrol             3  192000 km        6.0
2                   No    Petrol           1.3  200000 km        4.0
3                  Yes    Hybrid           2.5  168966 km        4.0
4                  Yes    Petrol           1.3   91901 km        4.0
...                ...       ...           ...        ...        ...
19232              Yes       CNG     2.0 Turbo  300000 km        4.0
19233              Yes    Petrol           2.4  161600 km        4.0
19234              Yes    Diesel             2  116365 km        4.0
19235              Yes    Diesel             2   51258 km        4.0
19236              Yes    Hybrid           2.4  186923 km        4.0

      Gear box type Drive wheels   Doors             Wheel   Color  Airbags
0         Automatic          4x4  04-May        Left wheel  Silver       12
1         Tiptronic          4x4  04-May        Left wheel   Black        8
2          Variator        Front  04-May  Right-hand drive   Black        2
3         Automatic          4x4  04-May        Left wheel   White        0
4         Automatic        Front  04-May        Left wheel  Silver        4
...             ...          ...     ...               ...     ...      ...
19232        Manual         Rear  02-Mar        Left wheel  Silver        5
19233     Tiptronic        Front  04-May        Left wheel     Red        8
19234     Automatic        Front  04-May        Left wheel    Grey        4
19235     Automatic        Front  04-May        Left wheel   Black        4
19236     Automatic        Front  04-May        Left wheel   White       12

[19237 rows x 18 columns]

In [ ]:
#menampilkan data  5 pertama dan data 5 terakhir
data

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,-,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000 km,4.0,Manual,Rear,02-Mar,Left wheel,Silver,5
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600 km,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365 km,4.0,Automatic,Front,04-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258 km,4.0,Automatic,Front,04-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923 km,4.0,Automatic,Front,04-May,Left wheel,White,12

In [ ]:
# 1. 
def dt1(i,j):
  P = 9
  Q = 0
  for col in ["Manufacturer", "Model", "Prod. year", "Category", "Fuel type", "Gear box type", "Doors", "Wheel", "Color"]:
    if data[col][i] == data[col][j]:
      Q += 1
  return (P-Q)/P

In [ ]:
print(dt1(1,2))
print(dt1(1,3))
print(dt1(1,4))

0.6666666666666666
0.5555555555555556
0.6666666666666666

In [ ]:
# Numerik
def dt2(i,j,h):
  result = 0
  for col in ["Price", "Cylinders", "Airbags"]:
    result = math.pow(abs(data[col][i] - data[col][j]), h)
  return result**(1/h)

In [ ]:
print(dt2(1,2,1))
print(dt2(1,3,1))
print(dt2(1,4,1))

6.0
8.0
4.0

In [ ]:
print(dt2(1,2,2))
print(dt2(1,3,2))
print(dt2(1,4,2))

6.0
8.0
4.0